defaults:
  - _self_
  - train: train
  - model: mobilenet
  
  - dataset: dataset
  - outputs: outputs
  - test: test

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}

aws:
  use_s3: false            
  region: eu-north-1       
  bucket: food101mini-data 