defaults:
  - _self_
  - train: train
  - model: mobilenet
  - dataset: dataset
  - outputs: outputs

hydra:
  mode: MULTIRUN
  run:
    dir: outputs/sweep_${now:%Y-%m-%d_%H-%M-%S}

aws:
  use_s3: false            
  region: eu-north-1       
  bucket: food101mini-data 

train:
  seed: 42
  batch_size: 64
  epochs: 10, 15
  loss: CrossEntropyLoss
  optimizer: 
    name: adam
    lr: 0.001, 0.003
unfreeze_layers: 3           # Number of last unfreeze layers
subset_percentage: 0.4, 0.8      # Percentage of dataset to use
augmentation: TrivialAugmentWide
early_stop_patience: 4

scheduler: 
  type: None, ReduceLROnPlateau                  # Options: None, ReduceLROnPlateau, StepLR
  step_size: 15
  gamma: 0.5

metrics: ["accuracy", "precision_macro", "recall_macro", "f1_macro"]

# Paths
data: ${dataset}   